### ISSUE TITLE
Menu in #1 with "good enough" UX

### ISSUE THREAD

**Issue by Jaytn** [Jaytn/VersammlungSkript#12]

**Comment by Jaytn** [comment]
@danielgross: Please add proper info text for dialogs.
- 		var response = ui.alert(
		"KDÄ Daten übermitteln",
		"PLACEHOLDER TEXT !!! NOCH BEARBEITEN\n\
    	Die Daten vom KDÄ werden in die Pläne übertragen\n\
   		 Fortfahren?",
		ui.ButtonSet.YES_NO)`
- 		ui.alert(
			"Nicht ausgeführt",
			"PLACEHOLDER TEXT !!! NOCH BEARBEITEN\n\
  	      Es wurde nichts gemacht.",
			ui.ButtonSet.OK)`

- 		ui.alert(
			"Ausgeführt",
			"PLACEHOLDER TEXT !!! NOCH BEARBEITEN\n\
        Die Daten vom KDÄ wurden in die Pläne übertragen.",
			ui.ButtonSet.OK)

**Comment by DanPlan** [comment]
vorgesehener Text hier: 
https://docs.google.com/document/d/12rxFREWOtr8NtxtzcRRX2PBIO4wz-mXzjPqYqSAX_Kk/edit

**Comment by Jaytn** [comment]
Danke, ich meinte aber den Text der in den ganzen Popups erscheint, auch die wenn auf "JA" oder "NEIN" geklickt wurde.
Habe die Dialoge mal aktiviert, dann siehst du was ich meine.

**Comment by DanPlan** [comment]
Text im Ja/nein Fenster passt

**Comment by DanPlan** [comment]
Bestätigung Ja: "Die Daten wurden übertragen"
Bestätigung Nein: "Es wurden keine Daten übertragen"

**Comment by Jaytn** [comment]
Done. Wenn es sonst keine Probleme / nötigen Verbesserungen mehr für die UX für KDÄ und ALDZ gibt, kann geschlossen werden
