### ISSUE TITLE
Hide previous weeks

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#19]
weeks in the past can be hidden for 3 weeks and then be deleted.

**Comment by Jaytn** [comment]
Wo meinst du das? (N°1? N°2? N°3)?

**Comment by DanPlan** [comment]
gute Frage. Ausblenden und löschen muss ich mir für jedes Dokument separat überlegen. 
Ich mach dann bei Gelegenheit ein neues Issue mit allen Angaben.
