### ISSUE TITLE
Drucken und Versand von #2

### ISSUE THREAD

**Issue by Jaytn** [Jaytn/VersammlungSkript#20]

**Comment by Jaytn** [comment]
possible options:
```
		format:pdf
		size:0
		fzr:true
		fzc:false
		portrait:false
		scale:3
		spct:1
		gridlines:true
		printnotes:true
		printtitle:false
		printdate:false
		printtime:false
		sheetnames:false
		pagenum:undefined
		pageorder:2
		attachment:false
		top_margin:0.75
		bottom_margin:0.75
		left_margin:0.25
		right_margin:0.25
		timestamp:42920.49709445602
		horizontal_alignment:CENTER
		vertical_alignment:TOP
		gridFiltersProto:[]
		gid:472840170
```
not sure if they really work - to be tested
probably must be POST

**Comment by Jaytn** [comment]
@DanPlan 
Wie in https://github.com/Jaytn/VersammlungSkript/issues/21#issuecomment-315395527 erwähnt, hab ich noch alte Einstellungen, passen die auch hier noch?
[HIER](https://drive.google.com/open?id=0Bx8esFM9ngiNX2Vwc3BGR0lYc28) ist wieder ein test Dokument.

Außerdem : das wird nur manuell versandt, oder? Also per knopf

**Comment by Jaytn** [comment]
@DanPlan eingebaut, bitte testen.
Sendet aktuell nur eine Mail an dich (und mich) - im Body steht dann an wen sie gegangen wäre.
Wenn Q/A passed, aktualisiere ich.

**Comment by Jaytn** [comment]
@DanPlan gibt's hierzu Rückmeldung? Dann könnten wir nötiges noch machen damit die nächsten Pläne schon reibungsloser laufen; und dann hier abschließen.

**Comment by DanPlan** [comment]
passt. 
Mailtext bitte wie folgt:

Betreff: "Vorsitz am [Datum Mittwoch]

"Lieber [Vorname Vorsitzender]

du bist am [Datum Mittwoch] eingeteilt, den Vorsitz über die Leben-Und-Dienst-Zusammenkunft zu übernehmen. Im Anhang findest du die Übersicht über die Aufgaben und Lerneinheiten.

Liebe Grüße
Deine Infotafel"

**Comment by DanPlan** [comment]
Noch etwas wäre cool: Kann man automatisieren, dass er nach erfolgtem Mail-Versand den Reiter unten grün einfärbt? 
(mein persönlicher Farbcode: 
- rot - angefangen nicht fertig 
- gelb - fertig nicht versandt 
- grün - versandt (bei #3 stell ich erst hierauf um, wenn auch ausgedruckt wurde)

**Comment by Jaytn** [comment]
Mail aktualisiert. Bitte noch bei den ersten (im Postausgang) schauen obs korrekt war.

bzgl farben... denke dafür machst du besser ne neue issue auf. weil das wird ja in allen plänen der fall sein denke ich & n°2 sollte evtl ja noch automatisch versendet werden (siehe #25)

**Comment by Jaytn** [comment]
See #39

**Comment by Jaytn** [comment]
@ #39
Das muss aber schon von Anfang an so sein, ich hab da nix geändert

**Comment by Jaytn** [comment]
Naja, sollte gefixed sein.

**Comment by DanPlan** [comment]
ich glaub das war auch von anfang an.

**Comment by Jaytn** [comment]
Scheint zu funktionieren (wenn keine wilden Leerzeichen auftauchen)
