### ISSUE TITLE
Drucken von #3

### ISSUE THREAD

**Issue by Jaytn** [Jaytn/VersammlungSkript#21]

**Comment by Jaytn** [comment]
see https://github.com/Jaytn/VersammlungSkript/issues/20#issuecomment-313256699 for details

**Comment by Jaytn** [comment]
@DanPlan 
ich hab noch diese einstellungen vom alten skript:
```
gridlines		= false
size 			= A4
fitw (fit to width) 	= true
```
passen die (zmd vorerst) noch? [HIER](https://drive.google.com/open?id=0Bx8esFM9ngiNRFBsZWtXWTFVQVU) ist ein test Dokument.

**Comment by Jaytn** [comment]
@DanPlan eingebaut. bitte testen.
aktuell speichert in [DIESEM](https://drive.google.com/drive/u/0/folders/0Bx8esFM9ngiNN3A0YTF5WE9wRlk) Folder, wenn Q/A bestanden, stelle ich auf live um

**Comment by Jaytn** [comment]
@DanPlan gibt's hierzu Rückmeldung? Dann könnten wir nötiges noch machen damit die nächsten Pläne schon reibungsloser laufen; und dann hier abschließen.

**Comment by DanPlan** [comment]
Schönheitsfehler: Bitte bei Veröffentlichung die Zeilen 12, 16 und 20 nochmal gesamt auf Weiß setzen. 
Anscheinend sind die bei jedem Plan unterschiedlich eingefärbt, was zu unterschiedlichen Kanten beim Balken darüber führt.

Sonst alles i.O.

**Comment by Jaytn** [comment]
Hängt das vlt zusammen mit #7 ?

**Comment by Jaytn** [comment]
Hatte ganz vergessen, den auf live umzustellen. Ist jetzt gemacht.
Wenns nochmal Probleme gibt, bitte diese Issue neu aufmachen.

Wegen den Farben bitte die andere Issue nutzen, oder ggf ne neue aufmachen.
