### ISSUE TITLE
#3 Fehlerhaftes Entfernen der Farben

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#27]
Beim Übertragen der Namen KDÄ und ALDZ werden die Farben aus den Namensfeldern ordentlich entfernt. Bei den Feldern in denen "Partner" und "Teilnehmer" steht passiert dies leider nicht (Felder: D16-18 und F16-18 in #3).

Ich finde es sehr gut, dass die blaue Farbe erst raus fliegt, wenn Einträge erfolgen. 
Dadurch vergisst man nichts.

**Comment by Jaytn** [comment]
Bei den Namen dürfte keine blaue Farbe sein, die rausfliegen könnte (war ja die Überlegung Farben in den anderen Plänen zu machen für was KDÄ / ALDZ noch nicht eingetragen haben - weil das aber ein umfangreichereres Feature ist, ist's für [Milestone 2](https://github.com/Jaytn/VersammlungSkript/milestone/2) nicht drin gewesen)
Bei Partner und Teilnehmer ist noch die Farbe weil das als Teil von #4 noch nicht eingebaut ist.
In n°3 hatte ich viel blau gelassen, um zu zeigen / erinnern, dass das Skript noch großenteils nicht fertig ist - das muss dann natürlich jede Woche manuell entfernt werden, wenn du willst können wir auch als Workaround vorerst das blau aus der Vorlage raus machen

**Comment by Jaytn** [comment]
Ich mach mal hier zu, falls du noch nicht fertig warst, kannst ja wieder aufmachen
