### ISSUE TITLE
#3 Anpassen abweichende Aufgabenzahl

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#28]
Uns-Im-Dienst-Verbessern:
Korrekt ausgeführt für: Wegfallen der Uhrzeiten in A17+18
Fehlerhaft ausgeführt in: Einträge in D17+18; F17+18 werden nicht entfernt (Partner/Teilnehmer)

Unser-Leben-Als-Christ:
Korrekt ausgeführt für: Uhrzeit in A22  - sehr gut ... war lange eine Baustelle, danke sehr.

**Comment by Jaytn** [comment]
> Uns-Im-Dienst-Verbessern:
> Korrekt ausgeführt für: Wegfallen der Uhrzeiten in A17+18
> Fehlerhaft ausgeführt in: Einträge in D17+18; F17+18 werden nicht entfernt (Partner/Teilnehmer)

Kein Bug, noch nicht implementiert (war ein Feature, das aufgefallen ist, nachdem Teile des Skript schon fertig waren) - wird in allen 3 Plänen simulatan implementiert, deshalb noch nicht gemacht.
 
> Unser-Leben-Als-Christ:
> Korrekt ausgeführt für: Uhrzeit in A22 - sehr gut ... war lange eine Baustelle, danke sehr.
Weiß nicht was du damit meinst aber OK.
