### ISSUE TITLE
BASISDATEN: vergangene Wochen autom. ausblenden

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#29]
Wochenübersicht. Man kann Montags automatisch die vergangenen Wochen ausblenden lassen.
Logs: Ausblenden, was 12 Wochen zurück liegt.

Überlegung: Prüfen ob das möglicherweise skript oder Formel crashes auslöst.
am Ende des Jahres könnte man dann manuell das Vorjahr löschen,
wenn keine chrashes, kann jede woche gelöscht werden was 6 wochen zurück liegt.
Logs: lieber nur jährliche Löschung

**Comment by Jaytn** [comment]
mögliches Duplikat von #19 ?

**Comment by DanPlan** [comment]
gute Frage. Ausblenden und löschen muss ich mir für jedes Dokument separat überlegen. 
Ich mach dann bei Gelegenheit ein neues Issue mit allen Angaben.
