### ISSUE TITLE
BASISDATEN: Optimierung

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#30]
möglicherweise Kombination verschiedener sheets

Wochenübersicht + MikroHistory
Pools in 1 Sheet zusammenfassen?

Email-Verteiler als 1 Datei?
NAME | EMAIL | #1 TRUE/FALSE | #2 TRUE/FALSE | #3 TRUE FALSE | etc.

**Comment by Jaytn** [comment]
Mir fällt grade auf, dass das wohl der Vorgänger von #44 ist.
Duplicate of #44
