### ISSUE TITLE
LE Formular Mails

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#33]
aktuell wird bei Nicht-Abschicken des LE Formulars eine Mail an mich geschickt und ich lauf dann den LEs hinterher um sie manuell einzutragen.

Änderungsvorschlag: Erinnerungsmail an den Vorsitzenden Freitag und Sonntag morgen. Montag Mail mit der Info dass es jetzt persönlich an Benjamin zurückgemeldet werden muss. 

Realistisch haben viele das Buch nicht dabei. Deshalb erfolgt die LE Vergabe oft nicht am selben Tag.
Ohne Buch kann eine neue LE aber nicht vergeben werden, weil man nicht weiß, welche bereits bearbeitet wurden. --> Idee entwickeln?

**Comment by Jaytn** [comment]
Ich glaub die Idee hatten wir schonmal, ich hatte nur erstmal nur auf dich gestellt um die Vorsitzenden nicht zu spammen - und dann ist es wohl untergegangen (hat ja soweit "funktioniert")
Im Moment wird wenn das Formular erneuert wird (montag 1am glaub?) die mail geschickt.

Mir wäre recht wenn wir das umstellen im Zuge vom neuen System für die LEs (bzw genauer gesagt "wenn wir uns ein neues überlegt haben")
Ich kann aber auch als quick fix einfach noch ein paar mails mehr verschicken lassen, wenn du jetzt was willst.

Überlegung... müssen wir mal machen, auf die schnelle hab ich keine wirkliche Idee, nur probleme. Da das Formular ja jede Woche neu gemacht wird - aus Einfachheit, damit die URL gleich bleibt, wofür ich auch weiterhin wäre - wir das mit nachtragen wohl nicht so einfach...
Vlt ein zweites Formular fürs Nachtragen, wo man dann die Woche auswählen kann? Das könnte einiges an Chaos in den Daten verbreiten...
Ich denke das könnten wir uns besser überlegen wenn wir schonmal ne genauere vorstellung haben wie die LEs am besten verwaltet werden.
Dazu (neues LE system) hab ich mir noch nicht viel Gedanken gemacht (außer "muss gemacht werden") - weiß auch nicht wie die Priorität dabei steht - ob die anderen noch fehlenden Funktionen vorrang haben?

**Comment by DanPlan** [comment]
neuer Text für die E-Mail: (Versand nur an Vorsitzenden)
[Prozessanpassung: 
Diese Mail an den Vorsitzenden (Kopie an mich zur Prozessüberwachung)
Beim Formularwechsel bitte andere Mail an ALDZ (Benjamin) und mich (siehe unten Teil 2)

ERSTE MAIL (Versand Samstag)
Betreff: "Erinnerung: Bitte neue Lerneinheiten melden."

Text:
"Lieber ... (Name des Vorsitzenden),

bisher sind noch keine neue Lerneinheiten übermittelt worden. 
Das Formular wird in der Nacht von Sonntag auf Montag auf die neue Woche umgestellt. 

Hier nochmal der Link zum Formular: [LINK]

Bitte trage bis spätestens Sonntag Abend alle Lerneinheiten ein, die bis dahin vergeben werden können.
Danach kann das Formular nicht mehr benutzt werden. Du kannst sie dann aber in einer einfachen E-mail an den Aufseher der Leben-und-Dienst-Zusammenkunft schicken.

Liebe Grüße
Deine Infotafel"




TEIL 2: Mail an ALDZ, Bei Neuerstellung des Formulars:

"Lieber Benjamin, 

Leider wurden die Lerneinheiten der letzten Woche noch nicht vom Vorsitzenden übermittelt. 
Bitte sprich ihn darauf an, damit sie nicht verloren gehen.

Liebe Grüße
Deine Infotafel"

**Comment by Jaytn** [comment]
Also...
Samstag (wieviel Uhr)?
überprüfen ob schon abgeschickt - wenn nicht Mail n°1 los an Vorsitz
Sonntag nacht
überprüfen ob schon abgeschickt - wenn nicht Mail n°2 los an ALDZ

Das würde dann natürlich nicht überprüfen, ob auch was eingetragen wurde - siehe #33 1.)

**Comment by DanPlan** [comment]
Samstag 9:00 AM (dann hat man noch Treffpunkt und Sonntagsversammlung um Brüder zu treffen)

Prüfung ob abgeschickt, war meine erste Idee.

Problem ist, dass ja oft nichts eingetragen wird (Teilnehmer ausgefallen etc), deshalb ist das LOG wichtig. Aber da sind die Brüder schon sorgfältig, sie warten halt nur immer bis alle Bücher da waren, bevor sie rückmelden und damit muss ich fast immer manuell machen - so müsste ich nur vereinzelte LEs nachtragen (bzw. Benny)

**Comment by Jaytn** [comment]
Die Sache ist, dass das LOG eigentlich nicht wirklich zum manuellen bearbeiten gedacht war, sondern eher zum nachgucken / nachvollziehen - theoretisch sollte da keiner rein müssen.
Da denke ich, wird das im Moment mehr rückwärts genutzt, alles manuell nachputzen damit das Skript funzt - was ja nicht der Sinn ist.

Überlegung als temporärer Workaround: Extra Formular, in dem man die Woche auswählen kann?
Wenn das ne Überlegung wert ist, machen wir neue Issue auf.

**Comment by Jaytn** [comment]
Die Emails sind mal eingebaut. Testweise aber erstmal nur an dich. Muss dann gecheckt werden obs ok ist.

**Comment by Jaytn** [comment]
Gemacht und getestet.
