### ISSUE TITLE
LE Form Liste

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#34]
Liste erweitern um Punkt "wird nachgereicht" ergibt keine Änderung. Vorsitzende schicken sonst gar nix wenn jemand kein Buch mit hat

**Comment by Jaytn** [comment]
Also gleicher Effekt wie "Teilnehmer Ausgefallen" ?

**Comment by DanPlan** [comment]
Korrektur: 
"Teilnehmer ausgefallen" wird einfach nur umbenannt in "Keine Zuteilung"
es muss kein neuer Punkt dazu kommen.
