### ISSUE TITLE
#1 automatisch einlesen

### ISSUE THREAD

**Issue by DanPlan** [Jaytn/VersammlungSkript#35]
Pläne stehen bei September Workbook, 
Oktober und November auf jw.org bereits erhältlich.
auch keine Auswahl für manuelles Einlesen verfügbar.

**Comment by Jaytn** [comment]
da ist noch kein automatismus gemacht - und die knöpfe sind manuell gemacht. 
weil das nicht nötig war um das skript "jetzt mal zum laufen zu bringen" - und dann vergessen / bzw nicht gedacht dass die nächsten schritte so lange verzögert sind

**Comment by Jaytn** [comment]
Hab als quick fix / workaround die knöpfe neu eingegeben mit neuen Monaten

**Comment by Jaytn** [comment]
(Siehe #45) Diese Issue ist für die Funktion:
Überprüfen ob es neue Arbeitshefte gibt - wenn ja in n°1 anfügen

@DanPlan Soll dafür wieder eine Mail verschickt werden? (Neue issue)

**Comment by Jaytn** [comment]
Das Skript im Testbereich hat so gut funktioniert, dass ich es direkt eingebaut habe.
Bitte noch im Auge behalten, ob nicht doch iwo ein Fehler entsteht

**Comment by Jaytn** [comment]
Da der Dezember auf Anhieb geklappt hat, mach ich hier mal zu.
